version: 2

project_name: recall

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

brews:
  - repository:
      owner: spider-hand
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "{{ .ProjectName }} v{{ .Version }}"
    directory: Formula
    homepage: "https://github.com/spider-hand/recall"
    description: "A CLI tool to find commands by describing what you want to do when you forget them"
    license: MIT
    install: |
      bin.install "recall"
    test: |
      system "#{bin}/recall", "--version"
